language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services:
  - memcached

sudo: false

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: phpunit
